export enum categories {
    medicine = '203783a4-58f2-4080-838b-8baf4f78c201',
    spa = '266cd448-dc6f-4fdb-9208-82586e4d01ce',
    kindergarten = '455f69ee-1a46-4f22-9650-5d44d39da8fb',
}

// Generated by https://quicktype.io
export interface LoginData {
    usuario:   string;
    contrasena: string;
}


export interface LoginResponse {
    id: string;
    usuario: string;
    contrasena: string;
    nombreCompleto: string;
    urlImagen: string;
    token: string;
}

export interface Usuario {
    id: string;
    usuario: string;
    contrasena: string;
    nombreCompleto: string;
    urlImagen: string;
    token: string;
}


// Servicios
// Generated by https://quicktype.io


export interface Category {
    id:       string;
    nombre:    string;
    urlImagen: string;
}

export interface Service {
    id: string;
    nombre: string;
    precio: number;
}

// Historico de servicios

export interface Categoria {
    id: string;
    nombre: string;
    urlImagen: string;
}

export interface Servicio {
    id: string;
    nombre: string;
    precio: number;
    categoria: Categoria;
}

export interface Profesional {
    id: string;
    usuario: string;
    nombreCompleto: string;
    urlImagen: string;
    roles: string[];
}


export interface HistoryService {
    id: string;
    servicio: Servicio;
    total: number;
    especie: string;
    nombrePaciente: string;
    fecha: string;
    profesional: Profesional;
}

export interface HistoryResponse {
    serviciosPrestados: HistoryService[];
    totalVentas: number;
}